/**
 * Static airport reference data.
 *
 * The `airports` table is the source of truth at runtime, but it only ships
 * with MIA seeded (see supabase/seed.sql), so any route line or airport marker
 * for a second airport silently resolved to nothing. This module is the
 * fallback the map reads when the table has no row for a code, and it is also
 * what seeds the table (scripts/generate-airport-seed.mjs).
 *
 * `surrounding: true` marks the airports drawn as ambient blobs on the map —
 * Florida fields near MIA. Everything else is here so that clicking a flight
 * can still highlight its origin/destination.
 *
 * Coordinates are the published airport reference points (ARP), WGS-84,
 * rounded to 4 decimals (~11 m).
 */

export interface AirportRef {
  iata: string;
  icao: string;
  name: string;
  city: string;
  country: string;
  lat: number;
  lon: number;
  tz: string;
  /** Drawn as an ambient blob on the MIA map. */
  surrounding?: boolean;
}

export const AIRPORTS: readonly AirportRef[] = [
  // ── South Florida & Florida (ambient blobs) ────────────────────────────
  {
    iata: "MIA",
    icao: "KMIA",
    name: "Miami International Airport",
    city: "Miami",
    country: "United States",
    lat: 25.7959,
    lon: -80.287,
    tz: "America/New_York",
    surrounding: true,
  },
  {
    iata: "FLL",
    icao: "KFLL",
    name: "Fort Lauderdale-Hollywood International Airport",
    city: "Fort Lauderdale",
    country: "United States",
    lat: 26.0742,
    lon: -80.1506,
    tz: "America/New_York",
    surrounding: true,
  },
  // PBI/KPBI was redesignated DJT/KDJT in 2025; flight feeds still emit PBI,
  // so the lookup key stays PBI. Coordinates verified against OurAirports.
  {
    iata: "PBI",
    icao: "KPBI",
    name: "Palm Beach International Airport",
    city: "West Palm Beach",
    country: "United States",
    lat: 26.6832,
    lon: -80.0956,
    tz: "America/New_York",
    surrounding: true,
  },
  {
    iata: "FXE",
    icao: "KFXE",
    name: "Fort Lauderdale Executive Airport",
    city: "Fort Lauderdale",
    country: "United States",
    lat: 26.1973,
    lon: -80.1707,
    tz: "America/New_York",
    surrounding: true,
  },
  {
    iata: "OPF",
    icao: "KOPF",
    name: "Miami-Opa Locka Executive Airport",
    city: "Opa-locka",
    country: "United States",
    lat: 25.907,
    lon: -80.2784,
    tz: "America/New_York",
    surrounding: true,
  },
  {
    iata: "TMB",
    icao: "KTMB",
    name: "Miami Executive Airport",
    city: "Miami",
    country: "United States",
    lat: 25.6479,
    lon: -80.4328,
    tz: "America/New_York",
    surrounding: true,
  },
  {
    iata: "HWO",
    icao: "KHWO",
    name: "North Perry Airport",
    city: "Hollywood",
    country: "United States",
    lat: 26.0012,
    lon: -80.2407,
    tz: "America/New_York",
    surrounding: true,
  },
  {
    iata: "PPM",
    icao: "KPMP",
    name: "Pompano Beach Airpark",
    city: "Pompano Beach",
    country: "United States",
    lat: 26.2471,
    lon: -80.1111,
    tz: "America/New_York",
    surrounding: true,
  },
  {
    iata: "BCT",
    icao: "KBCT",
    name: "Boca Raton Airport",
    city: "Boca Raton",
    country: "United States",
    lat: 26.3785,
    lon: -80.1077,
    tz: "America/New_York",
    surrounding: true,
  },
  {
    iata: "HST",
    icao: "KHST",
    name: "Homestead Air Reserve Base",
    city: "Homestead",
    country: "United States",
    lat: 25.4886,
    lon: -80.3836,
    tz: "America/New_York",
    surrounding: true,
  },
  {
    iata: "EYW",
    icao: "KEYW",
    name: "Key West International Airport",
    city: "Key West",
    country: "United States",
    lat: 24.5561,
    lon: -81.7596,
    tz: "America/New_York",
    surrounding: true,
  },
  {
    iata: "MTH",
    icao: "KMTH",
    name: "Florida Keys Marathon International Airport",
    city: "Marathon",
    country: "United States",
    lat: 24.7261,
    lon: -81.0514,
    tz: "America/New_York",
    surrounding: true,
  },
  {
    iata: "APF",
    icao: "KAPF",
    name: "Naples Municipal Airport",
    city: "Naples",
    country: "United States",
    lat: 26.1526,
    lon: -81.7753,
    tz: "America/New_York",
    surrounding: true,
  },
  {
    iata: "MRK",
    icao: "KMKY",
    name: "Marco Island Executive Airport",
    city: "Marco Island",
    country: "United States",
    lat: 25.995,
    lon: -81.6725,
    tz: "America/New_York",
    surrounding: true,
  },
  {
    iata: "IMM",
    icao: "KIMM",
    name: "Immokalee Regional Airport",
    city: "Immokalee",
    country: "United States",
    lat: 26.4332,
    lon: -81.401,
    tz: "America/New_York",
    surrounding: true,
  },
  {
    iata: "RSW",
    icao: "KRSW",
    name: "Southwest Florida International Airport",
    city: "Fort Myers",
    country: "United States",
    lat: 26.5362,
    lon: -81.7552,
    tz: "America/New_York",
    surrounding: true,
  },
  {
    iata: "PGD",
    icao: "KPGD",
    name: "Punta Gorda Airport",
    city: "Punta Gorda",
    country: "United States",
    lat: 26.9202,
    lon: -81.9905,
    tz: "America/New_York",
    surrounding: true,
  },
  {
    iata: "SRQ",
    icao: "KSRQ",
    name: "Sarasota-Bradenton International Airport",
    city: "Sarasota",
    country: "United States",
    lat: 27.3954,
    lon: -82.5544,
    tz: "America/New_York",
    surrounding: true,
  },
  {
    iata: "TPA",
    icao: "KTPA",
    name: "Tampa International Airport",
    city: "Tampa",
    country: "United States",
    lat: 27.9755,
    lon: -82.5332,
    tz: "America/New_York",
    surrounding: true,
  },
  {
    iata: "PIE",
    icao: "KPIE",
    name: "St. Pete-Clearwater International Airport",
    city: "St. Petersburg",
    country: "United States",
    lat: 27.9102,
    lon: -82.6874,
    tz: "America/New_York",
    surrounding: true,
  },
  {
    iata: "FPR",
    icao: "KFPR",
    name: "St. Lucie County International Airport",
    city: "Fort Pierce",
    country: "United States",
    lat: 27.4951,
    lon: -80.3683,
    tz: "America/New_York",
    surrounding: true,
  },
  {
    iata: "VRB",
    icao: "KVRB",
    name: "Vero Beach Regional Airport",
    city: "Vero Beach",
    country: "United States",
    lat: 27.6556,
    lon: -80.4179,
    tz: "America/New_York",
    surrounding: true,
  },
  {
    iata: "MLB",
    icao: "KMLB",
    name: "Melbourne Orlando International Airport",
    city: "Melbourne",
    country: "United States",
    lat: 28.1028,
    lon: -80.6453,
    tz: "America/New_York",
    surrounding: true,
  },
  {
    iata: "MCO",
    icao: "KMCO",
    name: "Orlando International Airport",
    city: "Orlando",
    country: "United States",
    lat: 28.4294,
    lon: -81.3089,
    tz: "America/New_York",
    surrounding: true,
  },
  {
    iata: "SFB",
    icao: "KSFB",
    name: "Orlando Sanford International Airport",
    city: "Sanford",
    country: "United States",
    lat: 28.7776,
    lon: -81.2375,
    tz: "America/New_York",
    surrounding: true,
  },
  {
    iata: "DAB",
    icao: "KDAB",
    name: "Daytona Beach International Airport",
    city: "Daytona Beach",
    country: "United States",
    lat: 29.1799,
    lon: -81.0581,
    tz: "America/New_York",
    surrounding: true,
  },
  {
    iata: "GNV",
    icao: "KGNV",
    name: "Gainesville Regional Airport",
    city: "Gainesville",
    country: "United States",
    lat: 29.6901,
    lon: -82.2718,
    tz: "America/New_York",
    surrounding: true,
  },
  {
    iata: "JAX",
    icao: "KJAX",
    name: "Jacksonville International Airport",
    city: "Jacksonville",
    country: "United States",
    lat: 30.4941,
    lon: -81.6879,
    tz: "America/New_York",
    surrounding: true,
  },
  {
    iata: "TLH",
    icao: "KTLH",
    name: "Tallahassee International Airport",
    city: "Tallahassee",
    country: "United States",
    lat: 30.3965,
    lon: -84.3503,
    tz: "America/New_York",
    surrounding: true,
  },
  {
    iata: "NAS",
    icao: "MYNN",
    name: "Lynden Pindling International Airport",
    city: "Nassau",
    country: "Bahamas",
    lat: 25.039,
    lon: -77.4662,
    tz: "America/Nassau",
    surrounding: true,
  },
  {
    iata: "FPO",
    icao: "MYGF",
    name: "Grand Bahama International Airport",
    city: "Freeport",
    country: "Bahamas",
    lat: 26.5587,
    lon: -78.6956,
    tz: "America/Nassau",
    surrounding: true,
  },
  {
    iata: "HAV",
    icao: "MUHA",
    name: "Jose Marti International Airport",
    city: "Havana",
    country: "Cuba",
    lat: 22.9892,
    lon: -82.4091,
    tz: "America/Havana",
    surrounding: true,
  },

  // ── United States mainland ─────────────────────────────────────────────
  {
    iata: "JFK",
    icao: "KJFK",
    name: "John F. Kennedy International Airport",
    city: "New York",
    country: "United States",
    lat: 40.6413,
    lon: -73.7781,
    tz: "America/New_York",
  },
  {
    iata: "LGA",
    icao: "KLGA",
    name: "LaGuardia Airport",
    city: "New York",
    country: "United States",
    lat: 40.7769,
    lon: -73.874,
    tz: "America/New_York",
  },
  {
    iata: "EWR",
    icao: "KEWR",
    name: "Newark Liberty International Airport",
    city: "Newark",
    country: "United States",
    lat: 40.6895,
    lon: -74.1745,
    tz: "America/New_York",
  },
  {
    iata: "BOS",
    icao: "KBOS",
    name: "Logan International Airport",
    city: "Boston",
    country: "United States",
    lat: 42.3656,
    lon: -71.0096,
    tz: "America/New_York",
  },
  {
    iata: "DCA",
    icao: "KDCA",
    name: "Ronald Reagan Washington National Airport",
    city: "Washington",
    country: "United States",
    lat: 38.8512,
    lon: -77.0402,
    tz: "America/New_York",
  },
  {
    iata: "IAD",
    icao: "KIAD",
    name: "Washington Dulles International Airport",
    city: "Washington",
    country: "United States",
    lat: 38.9531,
    lon: -77.4565,
    tz: "America/New_York",
  },
  {
    iata: "BWI",
    icao: "KBWI",
    name: "Baltimore/Washington International Airport",
    city: "Baltimore",
    country: "United States",
    lat: 39.1754,
    lon: -76.6682,
    tz: "America/New_York",
  },
  {
    iata: "PHL",
    icao: "KPHL",
    name: "Philadelphia International Airport",
    city: "Philadelphia",
    country: "United States",
    lat: 39.8744,
    lon: -75.2424,
    tz: "America/New_York",
  },
  {
    iata: "ATL",
    icao: "KATL",
    name: "Hartsfield-Jackson Atlanta International Airport",
    city: "Atlanta",
    country: "United States",
    lat: 33.6407,
    lon: -84.4277,
    tz: "America/New_York",
  },
  {
    iata: "CLT",
    icao: "KCLT",
    name: "Charlotte Douglas International Airport",
    city: "Charlotte",
    country: "United States",
    lat: 35.2144,
    lon: -80.9473,
    tz: "America/New_York",
  },
  {
    iata: "RDU",
    icao: "KRDU",
    name: "Raleigh-Durham International Airport",
    city: "Raleigh",
    country: "United States",
    lat: 35.8776,
    lon: -78.7875,
    tz: "America/New_York",
  },
  {
    iata: "ORD",
    icao: "KORD",
    name: "O'Hare International Airport",
    city: "Chicago",
    country: "United States",
    lat: 41.9742,
    lon: -87.9073,
    tz: "America/Chicago",
  },
  {
    iata: "MDW",
    icao: "KMDW",
    name: "Midway International Airport",
    city: "Chicago",
    country: "United States",
    lat: 41.7868,
    lon: -87.7522,
    tz: "America/Chicago",
  },
  {
    iata: "DFW",
    icao: "KDFW",
    name: "Dallas/Fort Worth International Airport",
    city: "Dallas",
    country: "United States",
    lat: 32.8998,
    lon: -97.0403,
    tz: "America/Chicago",
  },
  {
    iata: "IAH",
    icao: "KIAH",
    name: "George Bush Intercontinental Airport",
    city: "Houston",
    country: "United States",
    lat: 29.9902,
    lon: -95.3368,
    tz: "America/Chicago",
  },
  {
    iata: "DEN",
    icao: "KDEN",
    name: "Denver International Airport",
    city: "Denver",
    country: "United States",
    lat: 39.8561,
    lon: -104.6737,
    tz: "America/Denver",
  },
  {
    iata: "LAX",
    icao: "KLAX",
    name: "Los Angeles International Airport",
    city: "Los Angeles",
    country: "United States",
    lat: 33.9416,
    lon: -118.4085,
    tz: "America/Los_Angeles",
  },
  {
    iata: "SFO",
    icao: "KSFO",
    name: "San Francisco International Airport",
    city: "San Francisco",
    country: "United States",
    lat: 37.6213,
    lon: -122.379,
    tz: "America/Los_Angeles",
  },
  {
    iata: "SEA",
    icao: "KSEA",
    name: "Seattle-Tacoma International Airport",
    city: "Seattle",
    country: "United States",
    lat: 47.4502,
    lon: -122.3088,
    tz: "America/Los_Angeles",
  },
  {
    iata: "LAS",
    icao: "KLAS",
    name: "Harry Reid International Airport",
    city: "Las Vegas",
    country: "United States",
    lat: 36.084,
    lon: -115.1537,
    tz: "America/Los_Angeles",
  },
  {
    iata: "PHX",
    icao: "KPHX",
    name: "Phoenix Sky Harbor International Airport",
    city: "Phoenix",
    country: "United States",
    lat: 33.4352,
    lon: -112.0101,
    tz: "America/Phoenix",
  },
  {
    iata: "MSP",
    icao: "KMSP",
    name: "Minneapolis-St Paul International Airport",
    city: "Minneapolis",
    country: "United States",
    lat: 44.8848,
    lon: -93.2223,
    tz: "America/Chicago",
  },
  {
    iata: "DTW",
    icao: "KDTW",
    name: "Detroit Metropolitan Wayne County Airport",
    city: "Detroit",
    country: "United States",
    lat: 42.2124,
    lon: -83.3534,
    tz: "America/New_York",
  },
  {
    iata: "CLE",
    icao: "KCLE",
    name: "Cleveland Hopkins International Airport",
    city: "Cleveland",
    country: "United States",
    lat: 41.4117,
    lon: -81.8498,
    tz: "America/New_York",
  },
  {
    iata: "PIT",
    icao: "KPIT",
    name: "Pittsburgh International Airport",
    city: "Pittsburgh",
    country: "United States",
    lat: 40.4915,
    lon: -80.2329,
    tz: "America/New_York",
  },
  {
    iata: "CVG",
    icao: "KCVG",
    name: "Cincinnati/Northern Kentucky International Airport",
    city: "Cincinnati",
    country: "United States",
    lat: 39.0489,
    lon: -84.6678,
    tz: "America/New_York",
  },
  {
    iata: "STL",
    icao: "KSTL",
    name: "St. Louis Lambert International Airport",
    city: "St. Louis",
    country: "United States",
    lat: 38.7487,
    lon: -90.37,
    tz: "America/Chicago",
  },
  {
    iata: "MCI",
    icao: "KMCI",
    name: "Kansas City International Airport",
    city: "Kansas City",
    country: "United States",
    lat: 39.2976,
    lon: -94.7139,
    tz: "America/Chicago",
  },
  {
    iata: "BNA",
    icao: "KBNA",
    name: "Nashville International Airport",
    city: "Nashville",
    country: "United States",
    lat: 36.1263,
    lon: -86.6774,
    tz: "America/Chicago",
  },
  {
    iata: "IND",
    icao: "KIND",
    name: "Indianapolis International Airport",
    city: "Indianapolis",
    country: "United States",
    lat: 39.7173,
    lon: -86.2944,
    tz: "America/Indiana/Indianapolis",
  },
  {
    iata: "CMH",
    icao: "KCMH",
    name: "John Glenn Columbus International Airport",
    city: "Columbus",
    country: "United States",
    lat: 39.998,
    lon: -82.8919,
    tz: "America/New_York",
  },
  {
    iata: "AUS",
    icao: "KAUS",
    name: "Austin-Bergstrom International Airport",
    city: "Austin",
    country: "United States",
    lat: 30.1975,
    lon: -97.6664,
    tz: "America/Chicago",
  },
  {
    iata: "SAT",
    icao: "KSAT",
    name: "San Antonio International Airport",
    city: "San Antonio",
    country: "United States",
    lat: 29.5337,
    lon: -98.4698,
    tz: "America/Chicago",
  },
  {
    iata: "SAN",
    icao: "KSAN",
    name: "San Diego International Airport",
    city: "San Diego",
    country: "United States",
    lat: 32.7338,
    lon: -117.1933,
    tz: "America/Los_Angeles",
  },
  {
    iata: "MSY",
    icao: "KMSY",
    name: "Louis Armstrong New Orleans International Airport",
    city: "New Orleans",
    country: "United States",
    lat: 29.9934,
    lon: -90.258,
    tz: "America/Chicago",
  },
  {
    iata: "SJU",
    icao: "TJSJ",
    name: "Luis Munoz Marin International Airport",
    city: "San Juan",
    country: "Puerto Rico",
    lat: 18.4394,
    lon: -66.0018,
    tz: "America/Puerto_Rico",
  },
  {
    iata: "STT",
    icao: "TIST",
    name: "Cyril E. King Airport",
    city: "Charlotte Amalie",
    country: "U.S. Virgin Islands",
    lat: 18.3373,
    lon: -64.9734,
    tz: "America/St_Thomas",
  },
  {
    iata: "STX",
    icao: "TISX",
    name: "Henry E. Rohlsen Airport",
    city: "Christiansted",
    country: "U.S. Virgin Islands",
    lat: 17.7019,
    lon: -64.8055,
    tz: "America/St_Thomas",
  },

  // ── Caribbean ──────────────────────────────────────────────────────────
  {
    iata: "MBJ",
    icao: "MKJS",
    name: "Sangster International Airport",
    city: "Montego Bay",
    country: "Jamaica",
    lat: 18.5037,
    lon: -77.9134,
    tz: "America/Jamaica",
  },
  {
    iata: "KIN",
    icao: "MKJP",
    name: "Norman Manley International Airport",
    city: "Kingston",
    country: "Jamaica",
    lat: 17.9357,
    lon: -76.7875,
    tz: "America/Jamaica",
  },
  {
    iata: "PUJ",
    icao: "MDPC",
    name: "Punta Cana International Airport",
    city: "Punta Cana",
    country: "Dominican Republic",
    lat: 18.5674,
    lon: -68.3634,
    tz: "America/Santo_Domingo",
  },
  {
    iata: "SDQ",
    icao: "MDSD",
    name: "Las Americas International Airport",
    city: "Santo Domingo",
    country: "Dominican Republic",
    lat: 18.4297,
    lon: -69.6689,
    tz: "America/Santo_Domingo",
  },
  {
    iata: "STI",
    icao: "MDST",
    name: "Cibao International Airport",
    city: "Santiago",
    country: "Dominican Republic",
    lat: 19.4061,
    lon: -70.6047,
    tz: "America/Santo_Domingo",
  },
  {
    iata: "POP",
    icao: "MDPP",
    name: "Gregorio Luperon International Airport",
    city: "Puerto Plata",
    country: "Dominican Republic",
    lat: 19.7579,
    lon: -70.57,
    tz: "America/Santo_Domingo",
  },
  {
    iata: "PAP",
    icao: "MTPP",
    name: "Toussaint Louverture International Airport",
    city: "Port-au-Prince",
    country: "Haiti",
    lat: 18.58,
    lon: -72.2925,
    tz: "America/Port-au-Prince",
  },
  {
    iata: "CAP",
    icao: "MTCH",
    name: "Hugo Chavez International Airport",
    city: "Cap-Haitien",
    country: "Haiti",
    lat: 19.733,
    lon: -72.1947,
    tz: "America/Port-au-Prince",
  },
  {
    iata: "GCM",
    icao: "MWCR",
    name: "Owen Roberts International Airport",
    city: "George Town",
    country: "Cayman Islands",
    lat: 19.2928,
    lon: -81.3577,
    tz: "America/Cayman",
  },
  {
    iata: "AUA",
    icao: "TNCA",
    name: "Queen Beatrix International Airport",
    city: "Oranjestad",
    country: "Aruba",
    lat: 12.5014,
    lon: -70.0152,
    tz: "America/Aruba",
  },
  {
    iata: "CUR",
    icao: "TNCC",
    name: "Curacao International Airport",
    city: "Willemstad",
    country: "Curacao",
    lat: 12.1889,
    lon: -68.9598,
    tz: "America/Curacao",
  },
  {
    iata: "SXM",
    icao: "TNCM",
    name: "Princess Juliana International Airport",
    city: "Philipsburg",
    country: "Sint Maarten",
    lat: 18.041,
    lon: -63.1089,
    tz: "America/Lower_Princes",
  },
  {
    iata: "ANU",
    icao: "TAPA",
    name: "V. C. Bird International Airport",
    city: "St. John's",
    country: "Antigua and Barbuda",
    lat: 17.1367,
    lon: -61.7927,
    tz: "America/Antigua",
  },
  {
    iata: "BGI",
    icao: "TBPB",
    name: "Grantley Adams International Airport",
    city: "Bridgetown",
    country: "Barbados",
    lat: 13.0746,
    lon: -59.4925,
    tz: "America/Barbados",
  },
  {
    iata: "POS",
    icao: "TTPP",
    name: "Piarco International Airport",
    city: "Port of Spain",
    country: "Trinidad and Tobago",
    lat: 10.5954,
    lon: -61.3372,
    tz: "America/Port_of_Spain",
  },

  // ── Latin America ──────────────────────────────────────────────────────
  {
    iata: "MEX",
    icao: "MMMX",
    name: "Mexico City International Airport",
    city: "Mexico City",
    country: "Mexico",
    lat: 19.4363,
    lon: -99.0721,
    tz: "America/Mexico_City",
  },
  {
    iata: "CUN",
    icao: "MMUN",
    name: "Cancun International Airport",
    city: "Cancun",
    country: "Mexico",
    lat: 21.0365,
    lon: -86.8771,
    tz: "America/Cancun",
  },
  {
    iata: "GDL",
    icao: "MMGL",
    name: "Guadalajara International Airport",
    city: "Guadalajara",
    country: "Mexico",
    lat: 20.5218,
    lon: -103.3111,
    tz: "America/Mexico_City",
  },
  {
    iata: "MTY",
    icao: "MMMY",
    name: "Monterrey International Airport",
    city: "Monterrey",
    country: "Mexico",
    lat: 25.7785,
    lon: -100.1069,
    tz: "America/Monterrey",
  },
  {
    iata: "BZE",
    icao: "MZBZ",
    name: "Philip S. W. Goldson International Airport",
    city: "Belize City",
    country: "Belize",
    lat: 17.5391,
    lon: -88.3082,
    tz: "America/Belize",
  },
  {
    iata: "GUA",
    icao: "MGGT",
    name: "La Aurora International Airport",
    city: "Guatemala City",
    country: "Guatemala",
    lat: 14.5833,
    lon: -90.5275,
    tz: "America/Guatemala",
  },
  {
    iata: "SAL",
    icao: "MSLP",
    name: "El Salvador International Airport",
    city: "San Salvador",
    country: "El Salvador",
    lat: 13.4409,
    lon: -89.0558,
    tz: "America/El_Salvador",
  },
  {
    iata: "SAP",
    icao: "MHLM",
    name: "Ramon Villeda Morales International Airport",
    city: "San Pedro Sula",
    country: "Honduras",
    lat: 15.4526,
    lon: -87.9234,
    tz: "America/Tegucigalpa",
  },
  {
    iata: "TGU",
    icao: "MHTG",
    name: "Toncontin International Airport",
    city: "Tegucigalpa",
    country: "Honduras",
    lat: 14.0608,
    lon: -87.2172,
    tz: "America/Tegucigalpa",
  },
  {
    iata: "RTB",
    icao: "MHRO",
    name: "Juan Manuel Galvez International Airport",
    city: "Roatan",
    country: "Honduras",
    lat: 16.3167,
    lon: -86.523,
    tz: "America/Tegucigalpa",
  },
  {
    iata: "MGA",
    icao: "MNMG",
    name: "Augusto C. Sandino International Airport",
    city: "Managua",
    country: "Nicaragua",
    lat: 12.1415,
    lon: -86.1682,
    tz: "America/Managua",
  },
  {
    iata: "SJO",
    icao: "MROC",
    name: "Juan Santamaria International Airport",
    city: "San Jose",
    country: "Costa Rica",
    lat: 9.9981,
    lon: -84.2041,
    tz: "America/Costa_Rica",
  },
  {
    iata: "LIR",
    icao: "MRLB",
    name: "Daniel Oduber Quiros International Airport",
    city: "Liberia",
    country: "Costa Rica",
    lat: 10.5933,
    lon: -85.5444,
    tz: "America/Costa_Rica",
  },
  {
    iata: "PTY",
    icao: "MPTO",
    name: "Tocumen International Airport",
    city: "Panama City",
    country: "Panama",
    lat: 9.0714,
    lon: -79.3835,
    tz: "America/Panama",
  },
  {
    iata: "BOG",
    icao: "SKBO",
    name: "El Dorado International Airport",
    city: "Bogota",
    country: "Colombia",
    lat: 4.7016,
    lon: -74.1469,
    tz: "America/Bogota",
  },
  {
    iata: "MDE",
    icao: "SKRG",
    name: "Jose Maria Cordova International Airport",
    city: "Medellin",
    country: "Colombia",
    lat: 6.1645,
    lon: -75.4231,
    tz: "America/Bogota",
  },
  {
    iata: "CTG",
    icao: "SKCG",
    name: "Rafael Nunez International Airport",
    city: "Cartagena",
    country: "Colombia",
    lat: 10.4424,
    lon: -75.513,
    tz: "America/Bogota",
  },
  {
    iata: "BAQ",
    icao: "SKBQ",
    name: "Ernesto Cortissoz International Airport",
    city: "Barranquilla",
    country: "Colombia",
    lat: 10.8896,
    lon: -74.7808,
    tz: "America/Bogota",
  },
  {
    iata: "CLO",
    icao: "SKCL",
    name: "Alfonso Bonilla Aragon International Airport",
    city: "Cali",
    country: "Colombia",
    lat: 3.5432,
    lon: -76.3816,
    tz: "America/Bogota",
  },
  {
    iata: "CCS",
    icao: "SVMI",
    name: "Simon Bolivar International Airport",
    city: "Caracas",
    country: "Venezuela",
    lat: 10.6013,
    lon: -66.9911,
    tz: "America/Caracas",
  },
  {
    iata: "UIO",
    icao: "SEQM",
    name: "Mariscal Sucre International Airport",
    city: "Quito",
    country: "Ecuador",
    lat: -0.1292,
    lon: -78.3575,
    tz: "America/Guayaquil",
  },
  {
    iata: "GYE",
    icao: "SEGU",
    name: "Jose Joaquin de Olmedo International Airport",
    city: "Guayaquil",
    country: "Ecuador",
    lat: -2.1574,
    lon: -79.8836,
    tz: "America/Guayaquil",
  },
  {
    iata: "LIM",
    icao: "SPJC",
    name: "Jorge Chavez International Airport",
    city: "Lima",
    country: "Peru",
    lat: -12.0219,
    lon: -77.1143,
    tz: "America/Lima",
  },
  {
    iata: "SCL",
    icao: "SCEL",
    name: "Arturo Merino Benitez International Airport",
    city: "Santiago",
    country: "Chile",
    lat: -33.393,
    lon: -70.7858,
    tz: "America/Santiago",
  },
  {
    iata: "EZE",
    icao: "SAEZ",
    name: "Ministro Pistarini International Airport",
    city: "Buenos Aires",
    country: "Argentina",
    lat: -34.8222,
    lon: -58.5358,
    tz: "America/Argentina/Buenos_Aires",
  },
  {
    iata: "GRU",
    icao: "SBGR",
    name: "Sao Paulo/Guarulhos International Airport",
    city: "Sao Paulo",
    country: "Brazil",
    lat: -23.4356,
    lon: -46.4731,
    tz: "America/Sao_Paulo",
  },
  {
    iata: "GIG",
    icao: "SBGL",
    name: "Rio de Janeiro/Galeao International Airport",
    city: "Rio de Janeiro",
    country: "Brazil",
    lat: -22.81,
    lon: -43.2506,
    tz: "America/Sao_Paulo",
  },
  {
    iata: "BSB",
    icao: "SBBR",
    name: "Brasilia International Airport",
    city: "Brasilia",
    country: "Brazil",
    lat: -15.8711,
    lon: -47.9186,
    tz: "America/Sao_Paulo",
  },
  {
    iata: "MAO",
    icao: "SBEG",
    name: "Eduardo Gomes International Airport",
    city: "Manaus",
    country: "Brazil",
    lat: -3.0386,
    lon: -60.0497,
    tz: "America/Manaus",
  },

  // ── Canada ─────────────────────────────────────────────────────────────
  {
    iata: "YYZ",
    icao: "CYYZ",
    name: "Toronto Pearson International Airport",
    city: "Toronto",
    country: "Canada",
    lat: 43.6777,
    lon: -79.6248,
    tz: "America/Toronto",
  },
  {
    iata: "YUL",
    icao: "CYUL",
    name: "Montreal-Trudeau International Airport",
    city: "Montreal",
    country: "Canada",
    lat: 45.4706,
    lon: -73.7408,
    tz: "America/Toronto",
  },
  {
    iata: "YOW",
    icao: "CYOW",
    name: "Ottawa Macdonald-Cartier International Airport",
    city: "Ottawa",
    country: "Canada",
    lat: 45.3225,
    lon: -75.6692,
    tz: "America/Toronto",
  },
  {
    iata: "YVR",
    icao: "CYVR",
    name: "Vancouver International Airport",
    city: "Vancouver",
    country: "Canada",
    lat: 49.1947,
    lon: -123.1792,
    tz: "America/Vancouver",
  },
  {
    iata: "YHZ",
    icao: "CYHZ",
    name: "Halifax Stanfield International Airport",
    city: "Halifax",
    country: "Canada",
    lat: 44.8808,
    lon: -63.5086,
    tz: "America/Halifax",
  },

  // ── Europe, Middle East ────────────────────────────────────────────────
  {
    iata: "LHR",
    icao: "EGLL",
    name: "Heathrow Airport",
    city: "London",
    country: "United Kingdom",
    lat: 51.47,
    lon: -0.4543,
    tz: "Europe/London",
  },
  {
    iata: "LGW",
    icao: "EGKK",
    name: "Gatwick Airport",
    city: "London",
    country: "United Kingdom",
    lat: 51.1537,
    lon: -0.1821,
    tz: "Europe/London",
  },
  {
    iata: "DUB",
    icao: "EIDW",
    name: "Dublin Airport",
    city: "Dublin",
    country: "Ireland",
    lat: 53.4213,
    lon: -6.2701,
    tz: "Europe/Dublin",
  },
  {
    iata: "MAD",
    icao: "LEMD",
    name: "Adolfo Suarez Madrid-Barajas Airport",
    city: "Madrid",
    country: "Spain",
    lat: 40.4719,
    lon: -3.5626,
    tz: "Europe/Madrid",
  },
  {
    iata: "BCN",
    icao: "LEBL",
    name: "Josep Tarradellas Barcelona-El Prat Airport",
    city: "Barcelona",
    country: "Spain",
    lat: 41.2974,
    lon: 2.0833,
    tz: "Europe/Madrid",
  },
  {
    iata: "LIS",
    icao: "LPPT",
    name: "Humberto Delgado Airport",
    city: "Lisbon",
    country: "Portugal",
    lat: 38.7756,
    lon: -9.1354,
    tz: "Europe/Lisbon",
  },
  {
    iata: "CDG",
    icao: "LFPG",
    name: "Charles de Gaulle Airport",
    city: "Paris",
    country: "France",
    lat: 49.0097,
    lon: 2.5479,
    tz: "Europe/Paris",
  },
  {
    iata: "AMS",
    icao: "EHAM",
    name: "Amsterdam Airport Schiphol",
    city: "Amsterdam",
    country: "Netherlands",
    lat: 52.3105,
    lon: 4.7683,
    tz: "Europe/Amsterdam",
  },
  {
    iata: "BRU",
    icao: "EBBR",
    name: "Brussels Airport",
    city: "Brussels",
    country: "Belgium",
    lat: 50.9014,
    lon: 4.4844,
    tz: "Europe/Brussels",
  },
  {
    iata: "FRA",
    icao: "EDDF",
    name: "Frankfurt Airport",
    city: "Frankfurt",
    country: "Germany",
    lat: 50.0379,
    lon: 8.5622,
    tz: "Europe/Berlin",
  },
  {
    iata: "MUC",
    icao: "EDDM",
    name: "Munich Airport",
    city: "Munich",
    country: "Germany",
    lat: 48.3537,
    lon: 11.775,
    tz: "Europe/Berlin",
  },
  {
    iata: "ZRH",
    icao: "LSZH",
    name: "Zurich Airport",
    city: "Zurich",
    country: "Switzerland",
    lat: 47.4647,
    lon: 8.5492,
    tz: "Europe/Zurich",
  },
  {
    iata: "VIE",
    icao: "LOWW",
    name: "Vienna International Airport",
    city: "Vienna",
    country: "Austria",
    lat: 48.1103,
    lon: 16.5697,
    tz: "Europe/Vienna",
  },
  {
    iata: "FCO",
    icao: "LIRF",
    name: "Leonardo da Vinci-Fiumicino Airport",
    city: "Rome",
    country: "Italy",
    lat: 41.8003,
    lon: 12.2389,
    tz: "Europe/Rome",
  },
  {
    iata: "MXP",
    icao: "LIMC",
    name: "Milan Malpensa Airport",
    city: "Milan",
    country: "Italy",
    lat: 45.6301,
    lon: 8.7255,
    tz: "Europe/Rome",
  },
  {
    iata: "ATH",
    icao: "LGAV",
    name: "Athens International Airport",
    city: "Athens",
    country: "Greece",
    lat: 37.9364,
    lon: 23.9445,
    tz: "Europe/Athens",
  },
  {
    iata: "CPH",
    icao: "EKCH",
    name: "Copenhagen Airport",
    city: "Copenhagen",
    country: "Denmark",
    lat: 55.618,
    lon: 12.6508,
    tz: "Europe/Copenhagen",
  },
  {
    iata: "HEL",
    icao: "EFHK",
    name: "Helsinki-Vantaa Airport",
    city: "Helsinki",
    country: "Finland",
    lat: 60.3172,
    lon: 24.9633,
    tz: "Europe/Helsinki",
  },
  {
    iata: "WAW",
    icao: "EPWA",
    name: "Warsaw Chopin Airport",
    city: "Warsaw",
    country: "Poland",
    lat: 52.1657,
    lon: 20.9671,
    tz: "Europe/Warsaw",
  },
  {
    iata: "KEF",
    icao: "BIKF",
    name: "Keflavik International Airport",
    city: "Reykjavik",
    country: "Iceland",
    lat: 63.985,
    lon: -22.6056,
    tz: "Atlantic/Reykjavik",
  },
  {
    iata: "IST",
    icao: "LTFM",
    name: "Istanbul Airport",
    city: "Istanbul",
    country: "Turkey",
    lat: 41.2753,
    lon: 28.7519,
    tz: "Europe/Istanbul",
  },
  {
    iata: "TLV",
    icao: "LLBG",
    name: "Ben Gurion Airport",
    city: "Tel Aviv",
    country: "Israel",
    lat: 32.0114,
    lon: 34.8867,
    tz: "Asia/Jerusalem",
  },
  {
    iata: "DOH",
    icao: "OTHH",
    name: "Hamad International Airport",
    city: "Doha",
    country: "Qatar",
    lat: 25.2731,
    lon: 51.608,
    tz: "Asia/Qatar",
  },
  {
    iata: "DXB",
    icao: "OMDB",
    name: "Dubai International Airport",
    city: "Dubai",
    country: "United Arab Emirates",
    lat: 25.2532,
    lon: 55.3657,
    tz: "Asia/Dubai",
  },
];

const BY_IATA: ReadonlyMap<string, AirportRef> = new Map(
  AIRPORTS.map((airport) => [airport.iata, airport] as const)
);

/** Airports drawn as ambient blobs on the MIA map. */
export const SURROUNDING_AIRPORTS: readonly AirportRef[] = AIRPORTS.filter((a) => a.surrounding);

/** Look up static reference data for an IATA code. Case-insensitive. */
export function lookupAirport(iata: string | null | undefined): AirportRef | null {
  if (!iata) return null;
  return BY_IATA.get(iata.trim().toUpperCase()) ?? null;
}

/** Coordinates for an IATA code, or null when the airport is unknown. */
export function airportCoords(iata: string | null | undefined): [number, number] | null {
  const airport = lookupAirport(iata);
  return airport ? [airport.lat, airport.lon] : null;
}
