// Keep these projections aligned with `supabase/migrations/**` and
// `src/types/database.ts`. The dashboard is stringly typed at the query layer,
// so a stale column here can silently blank whole sections of the page.
export const FLIGHT_SNAPSHOT_COLUMNS = [
  "id",
  "flight_iata",
  "flight_icao",
  "flight_number",
  "airline_iata",
  "airline_name",
  "aircraft_icao",
  "aircraft_registration",
  "direction",
  "origin_iata",
  "origin_name",
  "destination_iata",
  "destination_name",
  "scheduled_departure",
  "actual_departure",
  "scheduled_arrival",
  "actual_arrival",
  "estimated_arrival",
  "status",
  "delay_minutes",
  "latitude",
  "longitude",
  "altitude_ft",
  "heading",
  "ground_speed_knots",
  "vertical_speed_fpm",
  "departure_terminal",
  "departure_gate",
  "arrival_terminal",
  "arrival_gate",
  "baggage_belt",
  "updated_at",
].join(",");

export const ANALYTICS_HOURLY_COLUMNS = [
  "id",
  "hour",
  "direction",
  "total_flights",
  "on_time",
  "delayed",
  "cancelled",
  "diverted",
  "avg_delay_minutes",
  "max_delay_minutes",
].join(",");

export const ANALYTICS_DAILY_COLUMNS = [
  "id",
  "date",
  "direction",
  "total_flights",
  "on_time",
  "delayed",
  "cancelled",
  "diverted",
  "avg_delay_minutes",
  "max_delay_minutes",
  "top_delayed_airline",
  "busiest_hour",
].join(",");

export const WEATHER_COLUMNS = [
  "id",
  "airport_iata",
  "observed_at",
  "temperature_c",
  "feels_like_c",
  "humidity_pct",
  "pressure_hpa",
  "wind_speed_knots",
  "wind_gust_knots",
  "wind_direction_deg",
  "visibility_km",
  "cloud_coverage_pct",
  "weather_code",
  "weather_description",
  "is_thunderstorm",
  "is_fog",
  "is_freezing",
  "precipitation_mm",
  "precipitation_probability",
  "data_source",
].join(",");

export const ANOMALY_COLUMNS = [
  "id",
  "anomaly_type",
  "severity",
  "title",
  "description",
  "metric_name",
  "metric_value",
  "baseline_value",
  "deviation_pct",
  "affected_flights",
  "affected_airlines",
  "affected_count",
  "is_active",
  "detected_at",
  "resolved_at",
  "detection_model",
].join(",");

export const PREDICTION_COLUMNS = [
  "id",
  "flight_iata",
  "scheduled_departure",
  "direction",
  "prediction_type",
  "predicted_value",
  "confidence",
  "factors",
  "model_version",
  "created_at",
  "expires_at",
].join(",");
